Fix email editor page render PHP error in PHP 7.4
PHP 7.4 doesn't support array spread.
error: Uncaught Error: Cannot unpack array with string keys
WOOPLUG-3953